name: Medito
description: A meditation learning tool

version: 3.1.6+30041
environment:
  sdk: ">=2.18.0 <3.7.0-13.0"
  flutter: ">=3.0.0"

dependencies:
  flutter:
    sdk: flutter
  app_settings: ^5.1.1
  audio_session: ^0.1.19
  audio_service: ^0.18.13
  auto_size_text: ^3.0.0-nullsafety.0
  back_button_interceptor: ^6.0.2
  cached_network_image: ^3.2.3
  connectivity_plus: ^6.0.3
  device_info_plus: ^9.0.2
  dio: ^5.4.0
  email_validator: '^2.1.16'
  equatable: ^2.0.0
  firebase_analytics: ^9.3.8
  firebase_core: ^1.24.0
  firebase_messaging: ^13.1.0
  flutter_dotenv: ^5.0.2
  flutter_downloader: ^1.10.2
  flutter_html: ^3.0.0-alpha.2
  flutter_local_notifications: ^17.2.2
  flutter_markdown: ^0.6.7
  flutter_riverpod: ^2.5.1
  flutter_svg: ^1.1.6
  flutter_timezone: ^1.0.8
  freezed: ^2.3.2
  freezed_annotation: ^2.2.0
  google_api_availability: ^5.0.0
  http: ^0.13.3
  image: ^4.0.17
  intl: ^0.19.0
  json_annotation: ^4.8.1
  just_audio: ^0.9.37
  package_info_plus: ^4.0.2
  path_provider: ^2.0.1
  pedantic: ^1.11.0
  permission_handler: ^11.3.1
  reorderables: ^0.6.0
  riverpod_annotation: ^2.3.4
  rxdart: ^0.27.1
  sentry_flutter: ^8.2.0
  share_plus: ^10.0.2
  shimmer: ^2.0.0
  shared_preferences: ^2.2.2
  timezone: ^0.9.3
  url_launcher: ^6.1.14

dependency_overrides:
  firebase_core_platform_interface: 4.5.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  pigeon: ^16.0.5
  mocktail: ^0.3.0
  build_runner: ^2.4.8
  riverpod_generator: ^2.3.9
  json_serializable: ^6.7.1
  dart_code_metrics: ^5.7.0
  #USAGE: dart run build_runner watch --delete-conflicting-outputs

flutter:
  assets:
    - assets/
    - .prod.env
    - .staging.env
    - assets/images/
  fonts:
    - family: Source Serif
      fonts:
        - asset: assets/fonts/source-serif/SourceSerif4-Regular.ttf
        - asset: assets/fonts/source-serif/SourceSerif4-Medium.ttf
        - asset: assets/fonts/source-serif/SourceSerif4-SemiBold.ttf
        - asset: assets/fonts/source-serif/SourceSerif4-Bold.ttf
    - family: DM Mono
      fonts:
        - asset: assets/fonts/dm-mono/DMMono-Medium.ttf
        - asset: assets/fonts/dm-mono/DMMono-Regular.ttf
    - family: DM Sans
      fonts:
        - asset: assets/fonts/dm-sans/DMSans-Bold.ttf
        - asset: assets/fonts/dm-sans/DMSans-Medium.ttf
        - asset: assets/fonts/dm-sans/DMSans-Regular.ttf
        - asset: assets/fonts/dm-sans/DMSans-SemiBold.ttf

  uses-material-design: true

# flutter build apk --release --no-tree-shake-icons