name: Medito
description: A meditation learning tool

# flutter build apk --release --no-tree-shake-icons
# flutter build ios --no-tree-shake-icons

version: 3.1.10+30046
environment:
  sdk: ">=2.18.0 <3.7.0-13.0"
  flutter: ">=3.0.0"

dependencies:
  flutter:
    sdk: flutter
  audio_session: ^0.1.19
  audio_service: ^0.18.13
  auto_size_text: ^3.0.0-nullsafety.0
  cached_network_image: ^3.2.3
  connectivity_plus: ^6.0.3
  device_info_plus: ^10.1.2
  dio: ^5.4.0
  email_validator: ^3.0.0
  equatable: ^2.0.0
  firebase_analytics: ^11.3.0
  firebase_core: ^3.4.0
  firebase_messaging: ^15.1.0
  flutter_dotenv: ^5.0.2
  flutter_downloader: ^1.10.2
  flutter_html: ^3.0.0-alpha.2
  flutter_local_notifications: ^17.2.2
  flutter_markdown: ^0.7.3+1
  flutter_riverpod: ^2.5.1
  flutter_svg: ^2.0.9
  flutter_timezone: ^3.0.1
  freezed: ^2.3.2
  freezed_annotation: ^2.2.0
  google_api_availability: ^5.0.0
  health: 11.0.0
  http: ^0.13.3
  image: ^4.0.17
  intl: ^0.19.0
  json_annotation: ^4.8.1
  just_audio: ^0.9.37
  package_info_plus: ^8.0.2
  path_provider: ^2.0.1
  pedantic: ^1.11.0
  permission_handler: ^11.3.1
  reorderables: ^0.6.0
  riverpod_annotation: ^2.3.4
  rxdart: ^0.27.1
  sentry_flutter: ^8.2.0
  shimmer: ^3.0.0
  shared_preferences: ^2.2.2
  timezone: ^0.9.3
  url_launcher: ^6.1.14
  flutter_stripe: ^11.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  pigeon: ^17.1.3
  mocktail: ^1.0.4
  build_runner: ^2.4.8
  riverpod_generator: ^2.3.9
  json_serializable: ^6.7.1
  dart_code_metrics: ^5.7.0

flutter:
  assets:
    - assets/
    - .prod.env
    - .staging.env
    - assets/images/
  fonts:
    - family: Source Serif
      fonts:
        - asset: assets/fonts/source-serif/SourceSerif4-Regular.ttf
        - asset: assets/fonts/source-serif/SourceSerif4-Medium.ttf
        - asset: assets/fonts/source-serif/SourceSerif4-SemiBold.ttf
        - asset: assets/fonts/source-serif/SourceSerif4-Bold.ttf
    - family: DM Mono
      fonts:
        - asset: assets/fonts/dm-mono/DMMono-Medium.ttf
        - asset: assets/fonts/dm-mono/DMMono-Regular.ttf
    - family: DM Sans
      fonts:
        - asset: assets/fonts/dm-sans/DMSans-Bold.ttf
        - asset: assets/fonts/dm-sans/DMSans-Medium.ttf
        - asset: assets/fonts/dm-sans/DMSans-Regular.ttf
        - asset: assets/fonts/dm-sans/DMSans-SemiBold.ttf

  uses-material-design: true